const flagUrl = (code) => `https://flagcdn.com/w80/${code}.png`;
async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`Could not load ${path}`);return response.json();}
function teamLine(team,winner){const isWinner=team.name===winner;return `<div class="team-line ${isWinner?'winner':''}"><img src="${flagUrl(team.flag)}" alt="" loading="lazy"><strong>${team.name}</strong><span class="points">${team.score}</span></div>`;}
function matchCard(match){return `<article class="match-card"><div class="match-top"><span>${match.date}</span><span>${match.stage}</span></div>${teamLine(match.teams[0],match.winner)}${teamLine(match.teams[1],match.winner)}</article>`;}
function leaderboardRow(row,index){return `<tr><td><span class="rank">${index+1}</span></td><td><strong>${row.name}</strong></td><td><strong>${row.total}</strong></td><td>${row.groupPoints}</td><td>${row.roundOf32Points}</td><td><span class="pill">${row.champion}</span></td></tr>`;}
function podiumCard(row,index){return `<article class="podium-card"><span class="rank">${index+1}</span><div><span class="label">${row.champion} champion pick</span><strong>${row.name}</strong></div><span class="points">${row.total}</span></article>`;}
function fixtureCard(fixture){const counts={};Object.values(fixture.picks).forEach((pick)=>{counts[pick]=(counts[pick]||0)+1});const chips=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([team,count])=>`<span class="pick-chip"><strong>${cleanTeam(team)}</strong> ${count}</span>`).join('');return `<article class="fixture-card"><div class="fixture-top"><span>Round of 32</span><span>${cleanTeam(fixture.home)} vs ${cleanTeam(fixture.away)}</span></div><div class="pick-list">${chips}</div></article>`;}
function cleanTeam(team){return String(team||'').replace('TÃ¼rkiye','Turkiye').replace('TÃ¼rkiye','Turkiye').replace('CÃ´te dâ€™Ivoire','Cote d’Ivoire').replace("CÃ´te d'Ivoire",'Cote d’Ivoire').replace('CuraÃ§ao','Curacao').trim();}
function groupByTeam(entries){const grouped=new Map();entries.forEach(({team,player,context})=>{const name=cleanTeam(team);if(!name)return;if(!grouped.has(name))grouped.set(name,{team:name,players:[],contexts:new Set()});const item=grouped.get(name);if(!item.players.includes(player))item.players.push(player);if(context)item.contexts.add(context);});return [...grouped.values()].map((item)=>({...item,contexts:[...item.contexts]})).sort((a,b)=>b.players.length-a.players.length||a.team.localeCompare(b.team));}
function teamPickCard(item){const chips=item.players.map((player)=>`<span class="person-chip">${player}</span>`).join('');const note=item.contexts.length?`<span class="team-context">${item.contexts.map(cleanTeam).join(', ')}</span>`:'';return `<article class="team-pick-card"><div class="team-pick-top"><strong>${item.team}</strong><span>${item.players.length}</span></div>${note}<div class="people-list">${chips}</div></article>`;}
function championPickCards(pool){const entries=pool.leaderboard.map((row)=>({team:row.champion,player:row.name}));return groupByTeam(entries).map(teamPickCard).join('');}
function roundOf32PickCards(pool){const entries=[];pool.roundOf32Picks.forEach((fixture)=>{Object.entries(fixture.picks).forEach(([player,team])=>entries.push({team,player,context:fixture.match}));});return groupByTeam(entries).map(teamPickCard).join('');}
async function render(){const [results,pool]=await Promise.all([loadJson('./data/results.json'),loadJson('./data/pool.json')]);document.querySelector('#lastUpdated').textContent=results.lastUpdated;document.querySelector('#stageName').textContent=results.stage;document.querySelector('#sourceLink').href=results.source.url;document.querySelector('#sourceLink').textContent=results.source.name;document.querySelector('#podium').innerHTML=pool.leaderboard.slice(0,3).map(podiumCard).join('');document.querySelector('#matchGrid').innerHTML=results.matches.map(matchCard).join('');document.querySelector('#leaderboardRows').innerHTML=pool.leaderboard.map(leaderboardRow).join('');document.querySelector('#championPickGrid').innerHTML=championPickCards(pool);document.querySelector('#teamPickGrid').innerHTML=roundOf32PickCards(pool);document.querySelector('#fixtureGrid').innerHTML=pool.roundOf32Picks.map(fixtureCard).join('');}
document.querySelector('#refreshButton').addEventListener('click',render);render().catch((error)=>{document.querySelector('#matchGrid').innerHTML=`<p>${error.message}</p>`;});
